name: Build and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn test:smoke
